spring.application.name=RoomBooking

# the room_booking database needs to be created manually before running the application
spring.datasource.url=jdbc:postgresql://localhost:5432/room_booking

#drop and create tables/columns, update schema
spring.jpa.hibernate.ddl-auto=update
#Print SQL queries to console
spring.jpa.show-sql=true

#springdoc.api-docs.enabled=true